#pragma once

// For Globle Definse in Rynex

// For def from Rynex only
// #define RY_DEV
#define RY_DISABLE_CODE_TODO 1	// Like Kommenting out
#define NOMINMAX

#define RY_CONSOLE 1
#define RY_CONSOLE_ALICATION_OFF_MEMORY 0
#define RY_CONSOLE_MOUSE_POSTION 0
#define RY_CONSOLE_WINDOW_SIZE 0
#define RY_CONSOLE_WINDOW_POSTION 0
#define RY_CONSOLE_LOG_NUMBER 0
// #define RY_SCRIPT_ENGINE
#define RY_ASSIMP_MODEL_LODER

#ifdef RY_CONSOLE_LOG_LARGE_NUMBER
	#define RY_CONSOLE_LOG_LARGE_NUMBER_GRUPING_SYMBOL ' '
	#define RY_CONSOLE_LOG_LARGE_NUMBER_GRUPING_COUNT "\3"
#endif

#define RY_DEV

// #define CODE_DISABLE
// #define NOT_FIXED

#ifdef RY_DEV
	#define RY_EDITOR_ASSET_FILEWATCHER 1
	// #define RY_WINDOW_PROZENT_SIZE	0.4
	#define RY_ENABLE_IMGUI 1

	#define RY_MAX_QUEUE_PER_FRAME 25u
	#define RY_MAX_THREAD_IN_USE 2u
	// #define RY_PARELE_GRAFIC_CONTEXT

	#define RY_IMGUI_DEMO_WINDOW 0
	#define RY_IMPLOT_DEMO_WINDOW 0

	
	#define RY_ENABLE_ASSERTS 1
	#define RY_ENABLE_ASSERTS_MSG 1
	#define RY_PROFILE 0
	#define RY_KONSOLE_FPS 0
	#define RY_ASSETMANGER_FILE_WATCHER 1
	
	// #define RY_CONSOLE_LOG_FUNKTION_OPENGL 0
	#define RY_ANABLE_RENDERER_ICONE 0
	#define RY_SCRIPTING_HAZEL 0
	#define RY_DISABLE_WEAK_PTR 0
	#define RY_ENABLE_WEBGPU_PILINE 0
	#define RY_ENABLE_FONT 1
	#define RY_EDITOR_ASSETMANGER_THREADE 1		// Debgu -> 0: time ~= 5s  | 1: time ~= 36s 
	#define RY_MODLE_MESH_INSTECENC_OPTI 1

	#define RY_ENABLE_BINDLES_TEXTURE 0
	#define RY_INSTECING 0
	#define RY_ENABLE_GARFIC_API_DBUGE_DETAILD_MASSEGES 0
	#define RY_ENABLE_GARFIC_API_DBUGE_MASSEGES 0 // Callback Funktion
	#define RY_ENABLE_GARFIC_API_DEBUG_MEASGE_DEBUG_BREAK 0 // Callback Funktion
	#define RY_ENABLE_GARFIC_API_DEBUG_MEASGE_DEBUG_BREAK_ERROR_TYPE 1
	#define RY_ENABLE_GARFIC_API_DEBUG_MEASGE_DEBUG_BREAK_PERFORMANCE_TYPE 0
	#define RY_ENABLE_GARFIC_API_CHECKS 1
	#define RY_ENABLE_GARFIC_API_CHECKS_LOOP 1
	#define RY_ENABLE_GARFIC_API_DRAW_CALL_CHECKS 0
	#define RY_GRAFIC_SUBMIT_TO_MAIN_THREAD_WITHE_OUT_WAIT 0

		// #define RY_OPENGL_USE_ARRAY_BUFFER
		// #define RY_OPENGL_OLD_UNIFORM

	#define RY_RENDER_3D 0

	#define RY_RENDER_2D 1
	#define RY_OLD_RENDER_FUNTION_SCENE_SYSTEM 1
	#define RY_ENABLE_DEFAULT_PROJECT
#ifndef RY_ENABLE_DEFAULT_PROJECT
	#define RY_DEFAULT_PROJECT_PATH
	#define RY_DEFAULT_PATH_TO_PROJECT(path) path
	#define RY_DEFAULT_PATH_PROJECT_FILE RY_DEFAULT_PROJECT_PATH
#else
	#define RY_DEFAULT_PROJECT_PATH "D:/dev/Rynex-Test-Projects/Test-Project-System/"
	#define RY_DEFAULT_PATH_TO_PROJECT(path) path
	#define RY_DEFAULT_PATH_PROJECT_FILE RY_DEFAULT_PROJECT_PATH "Test-Project-System.ryproj"
#endif
	#define RY_AKTIVATE_INTERAL_PATH 0
	#define RY_MODEL_IMPORTER_MATRIX_AXIS_FIX 0

	#define RY_ROBINE_HOOD_HASH_MAIN_MAP

	#define RY_CONSOLE_FUNC_FETURE_REMBER 0
	#define RY_CONSOLE_FUNC_FETURE_REMBER_PRINT 0



	// 
	

	#if RY_DISABLE_CODE_TODO
		#define RY_SERLIZE_MESH_COMP 1
		#define RY_ENABLE_SCRIPTING_MESH_COMP 0
		#define RY_RENDERER_API_INDEIPENDENT 0
		#define RY_STD_PTR_IMPL 1
		#define RY_TODO_APPLICATION_REMABER 1
		#define RY_TODO_APPLICATION_MULTI_THREAD 1
		#define RY_MESHSTRIPS 1
		#define RY_MESH 0
		#define RY_ENABLE_INSTANCE_BUFFER 1 // Mesh Source Flage
		#define RY_SCRIPT_PATH 0
		#define RY_PATH_IN_LINE 1
		#define RY_NEW_ASSET_REGISTER_SYSTEM 0
		#define RY_MAIN_THREAD_MAX_TASK_COUNT_QUEUE_PER_FRAME 0
		#define RY_MAIN_THREAD_MAX_TASK_TIME_QUEUE_PER_FRAME 1

	#endif
#endif

#ifdef NOT_FIXED_OR_DISABLE

	#ifdef CODE_DISABLE

		#define RY_STD_PTR_IMPL 1
		#define RY_EDITOR_ASSETMANGER_THREADE 1
	#endif


	#ifdef NOT_FIXED
		
	#endif

#endif



